# Generated by Django 6.0.2 on 2026-02-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameplayer_share_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_auto_split',
            field=models.BooleanField(default=True),
        ),
    ]
