version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mainyuk_postgres
    environment:
      POSTGRES_DB: mainyuk_db
      POSTGRES_USER: mainyuk_user
      POSTGRES_PASSWORD: mainyuk_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
